id: A9F9294BB
base_file: f24D2.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:57:10.847499
  last_modified_at: 2022-05-30 21:57:10.847513
